### ISSUE TITLE
Cannot connect to database?

### ISSUE THREAD

**Issue by Winsolider** [piyushparkash/FamilyTree#32]
the information of the database is right, why?

**Comment by piyushparkash** [comment]
Hi Winsolider

FamilyTree only Supports MySQL. I assume that you are using MySQL
If you have phpmyadmin or mysql console, try logging in with the credentials that you have mentioned during the installation of FamilyTree

Are you providing other details properly, such as host and database name?

Let me know if this helps.

**Comment by piyushparkash** [comment]
Hi @Winsolider 

Assuming that your issue is resolved since you have not replied.

Let me know if you are still facing issues.
