### ISSUE TITLE
Cannot create Tables

### ISSUE THREAD

**Issue by abubakergo** [piyushparkash/FamilyTree#39]
Error! All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead

Notice: Array to string conversion in /srv/disk6/2204896/www/familytree.biz.ht/template/template/compile/c06385065a6385f946f5059cadb6de60f90427fd.file.error_high.tpl.php on line 39

**Comment by piyushparkash** [comment]
Hi @abubakergo Can you please specify few details, which branch have you cloned?

**Comment by abubakergo** [comment]
the master branche

**Comment by piyushparkash** [comment]
Okay. I will look into it. Will try to fix it within EOD.

**Comment by abubakergo** [comment]
the full error message

xError! Something went wrong! We'll get this fixed soon 
Error Details
Message:Cannot create Tables
File:/srv/disk6/2204896/www/familytree.biz.ht/install/install.php
Line No:234
Context:
Notice: Array to string conversion in /srv/disk6/2204896/www/familytree.biz.ht/template/template/compile/c06385065a6385f946f5059cadb6de60f90427fd.file.error_high.tpl.php on line 39
Array

**Comment by abubakergo** [comment]
the screenshot

![img_6873](https://cloud.githubusercontent.com/assets/22264572/19598295/c865dbd8-97a2-11e6-834a-4c88897d5ece.PNG)

**Comment by piyushparkash** [comment]
Hi @abubakergo I did not see any issue with the SQL commands. Although I found one problem and fixed it. Can you please try the below steps and let me know the results.

`git pull` to get latest changes that I have made

`drop database <your-database>;` Drop database that you created for FamilyTree

`rm config.php` Remove the config file created and goto FamilyTree URL again to install it.

Let me know if you face problems again.

**Comment by piyushparkash** [comment]
Hi @abubakergo Were you able to resolve your issue?

**Comment by cdiaz** [comment]
I have the same problem

**Comment by piyushparkash** [comment]
@cdiaz See if there is config.php in Familytree root folder, delete it if it is there.

Make sure that there are no tables in database that you have mentioned in the FamilyTree.

**Comment by cdiaz** [comment]
The solution is add not null attribute on this line  https://github.com/piyushparkash/FamilyTree/blob/master/install/install.php#L253

**Comment by piyushparkash** [comment]
Great work @cdiaz. I will update the same in the repository.
