### ISSUE TITLE
Better direction on the first check of installation

### ISSUE THREAD

**Issue by piyushparkash** [piyushparkash/FamilyTree#40]
The very first thing which comes if we don't have appropriate permission is a bit misguiding. Need to improve it and make the text better with commands so that people can understand it better.

**Comment by CatherineEng** [comment]
I don't see anything aside from Page 404 after moving the files to their destination. I did not see a browser prompt to update folder permissions, though I did so anyway. All folders are now 744. There should be a prompt to create a database, is that right? I don't see one - though I could try to create one manually. What do you suggest?

**Comment by piyushparkash** [comment]
Could you help me with screenshot of the browser where you see 404 and the actual path where FamilyTree folder is residing for e.g. /var/www/FamilyTree or C:\wamp64\www\FamilyTree

**Comment by xupio** [comment]
Im new with the code and i received the attached screenshot
Can you help please

![Untitled](https://user-images.githubusercontent.com/48858391/58023070-f5d39e80-7b1f-11e9-83fd-99121b4b5eec.jpg)

**Comment by piyushparkash** [comment]
Hey @xupio just create 2 folders named cache and compile inside template folder. This error should vainsh post that.

**Comment by xupio** [comment]
I appreciate your kind support after that i received this 

![Untitled2](https://user-images.githubusercontent.com/48858391/58058956-192c3700-7b7c-11e9-95ed-e9a645a07a8c.jpg)

**Comment by ariyogilovers** [comment]
![image](https://user-images.githubusercontent.com/79570371/168982368-81363718-557a-414b-b5a7-fb38da54fd7e.png)
please help me?

**Comment by piyushparkash** [comment]
> I appreciate your kind support after that i received this
> 
> ![Untitled2](https://user-images.githubusercontent.com/48858391/58058956-192c3700-7b7c-11e9-95ed-e9a645a07a8c.jpg)

There should be confi.php created with your database details. Make sure that the credentials there are working.

**Comment by piyushparkash** [comment]
> ![image](https://user-images.githubusercontent.com/79570371/168982368-81363718-557a-414b-b5a7-fb38da54fd7e.png) please help me?

Please check 6th point in the README
