### ISSUE TITLE
something about wordpress

### ISSUE THREAD

**Issue by xiaodaokuailai** [piyushparkash/FamilyTree#44]
can i use it without wordpress?  it tell me input something about wordpress,i don't hava wordpress,but i cannot skip it.     how can i use it without wordpress?
<img width="615" alt="2017-02-08 3 13 02" src="https://cloud.githubusercontent.com/assets/11747642/22726945/1d654118-ee11-11e6-9f98-6bab516e25d5.png">

**Comment by piyushparkash** [comment]
Yes you can use.  `Admin Email` is the last required field. You can let all the other fields be empty  Do `git pull`

**Comment by piyushparkash** [comment]
Were you able to install?
