### ISSUE TITLE
Warning: fopen

### ISSUE THREAD

**Issue by iqqiang** [piyushparkash/FamilyTree#52]
Warning: fopen(template/cache/test_lock_file): failed to open stream: No such file or directory in D:\UPUPW_ANK_W64\WebRoot\Vhosts\3\FamilyTree\functions.php on line 51 Call Stack: 0.0000 260496 1. {main}() D:\UPUPW_ANK_W64\WebRoot\Vhosts\3\FamilyTree\index.php:0 0.0930 1655944 2. install->install(string(60)) D:\UPUPW_ANK_W64\WebRoot\Vhosts\3\FamilyTree\index.php:7 0.0930 1656288 3. install->check_directory_permission(null, null) D:\UPUPW_ANK_W64\WebRoot\Vhosts\3\FamilyTree\install\install.php:48 0.0930 1656528 4. dir_iswritable(string(14)) D:\UPUPW_ANK_W64\WebRoot\Vhosts\3\FamilyTree\install\install.php:69 0.0930 1656720 5. fopen(string(29), string(2)) D:\UPUPW_ANK_W64\WebRoot\Vhosts\3\FamilyTree\functions.php:51 Warning: fopen(template/compile/test_lock_file): failed to open stream: No such file or directory in D:\UPUPW_ANK_W64\WebRoot\Vhosts\3\FamilyTree\functions.php on line 51 Call Stack: 0.0000 260496 1. {main}() D:\UPUPW_ANK_W64\WebRoot\Vhosts\3\FamilyTree\index.php:0 0.0930 1655944 2. install->install(string(60)) D:\UPUPW_ANK_W64\WebRoot\Vhosts\3\FamilyTree\index.php:7 0.0930 1656288 3. install->check_directory_permission(null, null) D:\UPUPW_ANK_W64\WebRoot\Vhosts\3\FamilyTree\install\install.php:48 0.1100 1656800 4. dir_iswritable(string(16)) D:\UPUPW_ANK_W64\WebRoot\Vhosts\3\FamilyTree\install\install.php:78 0.1100 1656992 5. fopen(string(31), string(2)) D:\UPUPW_ANK_W64\WebRoot\Vhosts\3\FamilyTree\functions.php:51

config.php | Give Permission to the main Family Tree Directory
-- | --
cache/ | Give Permission to Template Cache directory (template/cache)
compile/ | Give Permission to Template Compilation directory (template/compile)

**Comment by piyushparkash** [comment]
It tries to check whether there is permission to create directly.  Just create template/cache and template/compile.
