### ISSUE TITLE
I am getting error as the Vendor folder is missing

### ISSUE THREAD

**Issue by kamleshpatani** [piyushparkash/FamilyTree#67]
Hi,

I am getting below error when i try to open page. 

Fatal error: Uncaught Error: Failed opening required 'C:\xampp\htdocs\FamilyTree/vendor/autoload.php'

**Comment by piyushparkash** [comment]
Hey @kamleshpatani, the dependencies are downloaded via composer.

Open terminal and goto the FamilyTree directory and run composer install. You might have to download and install composer.
