### ISSUE TITLE
Example of app

### ISSUE THREAD

**Issue by david-shiko** [piyushparkash/FamilyTree#70]
Hi!
I many times encounter a problem and now I met it again :) 
Some peoples (like me) want to explore an app before installing it to figure out is the app that we are looking for.
Can you please post examples of running app?

**Comment by ziabs** [comment]
https://familytree.ratupar.in/

**Comment by piyushparkash** [comment]
hi @david-shiko, You can find the demo link of OS Repos in the README. :)
